### ISSUE TITLE
The game tittles is getting dupiclate

### ISSUE THREAD

**Issue by ldelosreyesm** [dev-drprasad/hsk00#11]
When I add ROMs and click in Save changes, after in the list the game duplicates.
In the tv with the stick connected, the list shows the game is duplicated.

I used a U-BOX EMX-041

Also, some games are corrupted after the process, as lode runner, burger time...

**Comment by dev-drprasad** [comment]
Thanks for reporting issue. Can you attach dump of your SD card (with duplicate names) it will help me to debug the problem.

**Comment by dev-drprasad** [comment]
This has been fixed in v0.3.1. Download latest version from  https://github.com/dev-drprasad/hsk00/releases/latest. Thanks for reporting issue
